services:
  - type: web
    name: qr-upload-viewer-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://qr-upload-viewer.vercel.app
      - key: CORS_ORIGIN
        value: https://qr-upload-viewer.vercel.app
      - key: DATABASE_URL
        value: ./data/qr_viewer.db
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: ALLOWED_FILE_TYPES
        value: image/jpeg,image/png,image/gif,image/webp
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
      - key: QR_ERROR_CORRECTION
        value: M
      - key: QR_MARGIN
        value: 1
      - key: QR_WIDTH
        value: 256